name: Zombies
version: '1.0'
main: mc.minigame.Zombies
api-version: 1.18
depend:
  - Vault
commands:
  jail:
    usage: /jail <player>
    aliases:
      - j
    description: Puts a player into jail ;]
  givemoney:
    description: Add money
    usage: /givemoney <Player> <money>
  removemoney:
    description: Remove money
    usage: /removemoney <Player> <money>
  giveset:
    description: Get your armor
    usage: /giveset [armorType]
  spawnzombie:
    description: Spawn zombies on map radius
    usage: /spawnzombie [number of zombies]
  setTimer:
    description: Set timer
    usage: /setTimer
  startgame:
    description: Start the game
    usage: /startgame
  stopgame:
    description: Stop the game
    usage: /stopgame
