name: Zombies
version: '1.0'
main: mc.minigame.Zombies
api-version: 1.18
commands:
  setmoney:
    description: Set your money
    usage: /setmoney <money>
  giveset:
    description: Get your armor
    usage: /giveset [armorType]
  spawnzombie:
    description: Spawn zombies on map radius
    usage: /spawnzombie [number of zombies]
  setTimer:
    description: Set timer
    usage: /setTimer
